name: Documentation
on:
  pull_request:
    branches:
      - dev

jobs:
  build-doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - name: Generating doc
        run: |
          npm run docs
      - name: Commit documentation changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "DOC: Automated documentation push"
          commit_options: "--no-verify"
